//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public string unidad { get; set; }
        public double cantidad { get; set; }
        public int estado { get; set; }
    }
}
