//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public int puesto { get; set; }
    
        public virtual tbRoles tbRoles { get; set; }
    }
}
